name: dotnet build pipeline to Check the vulnerable pacakges and report

on:
    push:
        branches:
            [ main ]
        paths:
            - 'Saga-Pattern-MassTransit'
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v2
            
            - name: Setup .Net
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '9.0'
            
            - name: Restore Dependencies
              working-directory: Saga-Pattern-MassTransit
              run: dotnet restore

            - name: Checking NuGet package vulnerabilities in proj
              working-directory: Saga-Pattern-MassTransit
              run: |
                dotnet list package --vulnerable --include-transitive > build.log
                echo "Analyze dotnet list package command log output"
                if grep -q "has the following vulnerable packages" build.log; then
                    echo "Security vulnerabilities found on the log output" 
                    cat build.log
                    exit 1
                else
                    echo "No Security vulnerabilities found"
                    cat build.log
                fi
            
            - name: Build the solution
              working-directory: Saga-Pattern-MassTransit
              run: dotnet build --no-restore -c Release
